add Activity
PfadiMH/site pull request #23
Opened 2024-04-12 13:01 UTC by cediackermann

2024-04-12 13:02 UTC, TeamBattino requested changes

2024-04-12 13:02 UTC, TeamBattino commented on Bash Scripting Language.md
Nooooooo

2024-04-30 14:08 UTC, TeamBattino approved these changes
looks good

2024-05-02 07:25 UTC, silvio2402 requested changes

2024-05-02 07:25 UTC, silvio2402 commented on components/Sections/Activity/Activity.tsx
> +import style from "./Activities.module.css";
Here you import `./Activities.module.css`, but the actual file name is `./Activity.module.css`.

2024-05-02 07:25 UTC, silvio2402 commented on components/Sections/Activity/Activity.tsx
> +  const activities = await prisma.activities.findFirst({
Rename this to `activity` since it's referring to one activity.

2024-05-02 09:23 UTC, merged